# Generated by Django 5.2.17 on 2026-09-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
