# Generated by Django 5.2.17 on 2026-09-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_invitee_email_alter_invitee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninvitee',
            name='rsvp_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('UNDECIDED', 'Undecided')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
